# Site settings
title: Lei Wang
url: "https://tristone13th.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
timezone: Asia/Shanghai

# Your information
# email: tristone13th@outlook.com
author: Lei Wang
avatar: "../img/avatar.jpg"
profile: 求物之妙，如系风捕景，能使是物了然于心者，千万人而不一遇也。
# twitter_username: twitter_username
# github_username:  tristone13th
profile_links:
  GitHub: "https://github.com/tristone13th"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service: 多说
# choose one and un-comment the line to active it
# disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
# duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    Donate: /donate/

permalink: /archivers/:title

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: CommonMarkGhPages

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]
